# Generated by Django 5.0.1 on 2025-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("aqi_value", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Biodiversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("ecosystem_strength", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sustainability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("green_cover", models.FloatField()),
                ("water_stress", models.FloatField()),
                ("aqi", models.IntegerField()),
            ],
        ),
    ]
