# Generated by Django 5.0.1 on 2025-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0002_airquality_biodiversity_sustainability"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airquality",
            name="status",
        ),
        migrations.AddField(
            model_name="sustainability",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="biodiversity",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
