# Generated by Django 5.0.1 on 2025-09-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0003_remove_airquality_status_sustainability_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
