# Generated by Django 5.0.1 on 2025-09-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0004_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreeningOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("date", models.DateField()),
                ("ndvi", models.FloatField(blank=True, null=True)),
                ("green_cover", models.FloatField(blank=True, null=True)),
                ("needs_greening", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SolarSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("date", models.DateField()),
                (
                    "ghi_kwh_m2_day",
                    models.FloatField(
                        help_text="Global Horizontal Irradiance (kWh/m²/day)"
                    ),
                ),
                (
                    "dni_kwh_m2_day",
                    models.FloatField(
                        blank=True,
                        help_text="Direct Normal Irradiance (kWh/m²/day)",
                        null=True,
                    ),
                ),
                ("suitability", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="WaterResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("river", "River/Stream"),
                            ("reservoir", "Reservoir/Dam"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("geom_geojson", models.JSONField()),
                ("props", models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
