# Generated by Django 5.0.1 on 2025-09-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0005_greeningopportunity_solarsite_waterresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("flood", "Flood Risk"),
                            ("rainfall", "Rainfall Risk"),
                            ("drought", "Drought Zone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "geom_geojson",
                    models.JSONField(
                        help_text="GeoJSON geometry: Polygon or MultiPolygon"
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
