# Generated by Django 5.0.1 on 2025-09-23 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0006_riskzone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("household", "Household"),
                            ("store", "Store / Bakery / Restaurant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=250)),
                ("city", models.CharField(default="Chattogram", max_length=100)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecipientSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("contact", models.CharField(blank=True, max_length=150)),
                ("city", models.CharField(default="Chattogram", max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("daily_capacity_kg", models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name="FoodOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("quantity_kg", models.FloatField()),
                ("ready_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("collected", "Collected"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "store",
                    models.ForeignKey(
                        limit_choices_to={"kind": "store"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_offers",
                        to="UA.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_kg", models.FloatField()),
                ("distance_km", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("confirmed", "Confirmed"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="UA.foodoffer",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="UA.recipientsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WasteEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("organic", "Organic"),
                            ("recyclable", "Recyclable"),
                            ("landfill", "Landfill"),
                            ("food", "Food Waste"),
                            ("hazard", "Hazardous (special handling)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("weight_kg", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_entries",
                        to="UA.profile",
                    ),
                ),
            ],
        ),
    ]
