# Generated by Django 5.0.1 on 2025-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UA", "0009_userextra_delete_citizen"),
    ]

    operations = [
        migrations.AddField(
            model_name="userextra",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userextra",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userextra",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
